language: python
python:
  - 2.7
  - 3.4
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libnetcdf-dev
install:
  - pip install -r test_requirements.txt
  - pip install .
script:
  - py.test -v tests
